---
title: "metaAnalysis_pcawg_mm_AX001_KX001_KX002_KX003_TX001_TX002_CB001 April, 2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache=TRUE, fig.path="./graphics/plot",autodep=TRUE,fig.width=5, fig.height=4)
knitr::opts_knit$set(root.dir = '/Users/hm8/sanger/lymphocyteExpansionSequenceAnalysis/metaAnalysis_pcawg_mm_AX001_KX001_KX002_KX003_TX001_TX002_CB001_March2021/hdp')
library(ggplot2)
library(cowplot)
library(caTools)
library(reshape2)
library(dplyr)
library(hdp)
library(RColorBrewer)
library(grid)
library(gridExtra)
library(ggpubr)
location="farm"
#location="local"

if (location=="farm"){
  root="/lustre/scratch116/casm/cgp/users/hm8"
} else if (location=="local"){
  root="/Users/hm8/volumes/hm8_network"
} else {
  warning("location not set- using current directory")
  root=getwd()
}
```





###### load in data
```{r, message=FALSE, warning=FALSE}
groupname="pcawg_lymph_hsc"
name_sigs = "noprior"
my_prior=""

system("mkdir -p figures")
#luad_multi, samp_type, sig_propCI, dp_distn, comp_trinuc, Nsig, 
load(file=paste("/Users/hm8/volumes/hm8_network/lymphocyteWGS/metaAnalysis_pcawg_mm_AX001_KX001_KX002_KX003_TX001_TX002_CB001_March2021/hdp/luad_multi.", name_sigs, ".", groupname, ".Rdata", sep="") )
#sig_propCI,samp_type,sig_prop, 
load(file=paste("/Users/hm8/volumes/hm8_network/lymphocyteWGS/metaAnalysis_pcawg_mm_AX001_KX001_KX002_KX003_TX001_TX002_CB001_March2021/hdp/misc_samp_prop_objects.", groupname, ".Rdata", sep="") )

### Checking burn-in, etc
par(mfrow=c(2,2))
p1 <- lapply(chains(luad_multi), plot_lik, bty='L', start=10) # check for convergence (if not, increase burnin)- 20K is good
p2 <- lapply(chains(luad_multi), plot_numcluster, bty='L')
p3 <- lapply(chains(luad_multi), plot_data_assigned, bty='L')
# Only needs 10K, for future reference

# Extract components (mutational signatures)
mut_colours <- c(RColorBrewer::brewer.pal(10, 'Paired')[seq(1,10,2)], 'grey70')
par(mfrow=c(1,1), mar=c(5, 4, 4, 2))
plot_comp_size(luad_multi, bty="L")
trinuc_context <- sapply(strsplit(colnames(mut_count), '\\.'), `[`, 4)
group_factor <- as.factor(rep(c("C>A", "C>G", "C>T", "T>A", "T>C", "T>G"),
                              each=16))
Ncolumns = ceiling(sqrt(Nsig))
Nrows = ceiling(Nsig/Ncolumns)
pdf(file=paste("figures/signatures",name_sigs,"_prior", my_prior, "_", groupname, "_componentsSpectra.pdf", sep=""), width=Ncolumns*3, height=Nrows*2)
par(mfrow=c(Nrows,Ncolumns))
par(mar=c(3,3,3,1))
plot_comp_distn(luad_multi, cat_names=trinuc_context,
                  grouping=group_factor, col=mut_colours,
                  col_nonsig="grey80", show_group_labels=TRUE)
dev.off()

# Save mutational spectrum for components
comp_distn <- comp_categ_distn(luad_multi)
write.table(t(comp_distn$mean), file=paste("mutspectrum_components.comp_distn_mean.", name_sigs, ".", groupname, ".txt", sep=""), col.names = T, row.names = F, quote=F)
```


## Plot exposures
```{r, message=FALSE, warning=FALSE}

{pdf(file=paste("figures/plot_dp_comp_exposure_", name_sigs,"_prior", my_prior, groupname, ".pdf", sep="") )
plot_dp_comp_exposure(luad_multi, samp_type$dpindex, incl_nonsig = F,
                      col=c('black', RColorBrewer::brewer.pal(12, "Paired"),  RColorBrewer::brewer.pal(8, "Dark2"),  RColorBrewer::brewer.pal(10, "Set1"), "orange","pink", "red","green","blue"))
}
plot_dp_comp_exposure(luad_multi, samp_type$dpindex, incl_nonsig = F,
                      col=c('black', RColorBrewer::brewer.pal(10, "Paired"), RColorBrewer::brewer.pal(10, "Set1"), "orange","pink", "red", rep("grey", times=25) ))
```


## Calculate cosine similarity of new signatures to preexisting Cosmic and PCAWG signatures
```{r, message=FALSE, warning=FALSE}
####### Loading COSMIC signatures
cosmic.sigs = read.table('/Users/hm8/sanger/example_code/nicola_hdp/signatures_probabilities.txt', header=TRUE, sep='\t')
cosmic.sigs = cosmic.sigs[order(cosmic.sigs$Substitution.Type, cosmic.sigs$Trinucleotide),]

####### Loading blood signature
bloodsig = read.table("/Users/hm8/sanger/lymphocyteExpansionSequenceAnalysis/bloodsignature_analysis/BloodSig_analysis_Aug2020/sigfit_cosmic2_bloodsig_Aug2020.txt", header=T, stringsAsFactors = F, sep="\t")
colnames(bloodsig)[2] = "SBSblood"
# put in order of cosmic sigs
#rownames(bloodsig) = bloodsig$Somatic.Mutation.Type
#bloodsigO = bloodsig[cosmic.sigs$Somatic.Mutation.Type,]
prior_sigsC <- data.frame(as.matrix(cosmic.sigs[,grep('Signature', colnames(cosmic.sigs))]), Signature.blood = bloodsig$SBSblood)
# number of signatures: 31


######## Loading PCAWG signatures
pcawg.sigs <- read.csv('/Users/hm8/sanger/example_code/nicola_hdp/sigProfiler_SBS_signatures_2018_03_28.csv', header=TRUE)
#  sort by Substitution Type and Trinucleotide
pcawg.sigs <- pcawg.sigs[order(pcawg.sigs$Type, pcawg.sigs$SubType),]
prior_sigsP1 <- as.matrix(pcawg.sigs[,grep('SB', colnames(pcawg.sigs))])
# number of prior signatures to condition on (65)
# each col (signatures) must sum to 1 (over all mutation types)
colsum1 = apply(prior_sigsP1, MARGIN=2, FUN=sum)
prior_sigsP = prior_sigsP1
for (i in 1:length(colsum1)){
  prior_sigsP[,i] = prior_sigsP1[,i]/colsum1[i]
}
bloodsig = read.table("/Users/hm8/sanger/lymphocyteExpansionSequenceAnalysis/bloodsignature_analysis/BloodSig_analysis_Aug2020/sigfit_bloodsig_Aug2020.txt", header=T, stringsAsFactors = F, sep="\t")
colnames(bloodsig)[2] = "SBSblood"
prior_sigsP = data.frame(prior_sigsP, Signature.blood = bloodsig$SBSblood)


library("lsa")
cosmic_cosine = matrix(ncol=Nsig, nrow = ncol(prior_sigsC))
pcawg_cosine = matrix(ncol=Nsig, nrow = ncol(prior_sigsP))
for (i in 1:Nsig){
  cosmic_cosine[,i] = apply(prior_sigsC, MARGIN=2, FUN=function(X) cosine(X, comp_trinuc[[1]][i,]) )  
  pcawg_cosine[,i] = apply(prior_sigsP, MARGIN=2, FUN=function(X) cosine(X, comp_trinuc[[1]][i,]) )
}

# {pdf(file=paste("figures/signatures",name_sigs,"_prior", my_prior, "_", groupname, "_cosine_sim_Cosmic.pdf", sep=""), width=Ncolumns*1.8, height=Nrows*1.5)
# par(mfrow=c(Nrows,Ncolumns))
# par(mar=c(3,3,3,1))
# for (i in 1:Nsig){
#   hist(cosmic_cosine[,i], main=paste("C:",row.names(comp_trinuc[[1]])[i], " cos=",signif(max(cosmic_cosine[,i]), 2), " S:", which(cosmic_cosine[,i]==max(cosmic_cosine[,i])), sep=""), xlab="cosine sim.", col="grey", breaks=15)
# } }
# 
# {pdf(file=paste("figures/signatures",name_sigs,"_prior", my_prior, "_", groupname, "_cosine_sim_PCAWG.pdf", sep=""), width=Ncolumns*1.8, height=Nrows*1.5)
# par(mfrow=c(Nrows,Ncolumns))
# par(mar=c(3,3,3,1))
# for (i in 1:Nsig){
#   hist(pcawg_cosine[,i], main=paste("C:",row.names(comp_trinuc[[1]])[i], " cos=",signif(max(pcawg_cosine[,i]), 2), " ", colnames(prior_sigsP)[which(pcawg_cosine[,i]==max(pcawg_cosine[,i]))], sep=""), xlab="cosine sim.", col="grey", breaks=15)
# } }

cosmic_cosine_list = list()
pcawg_cosine_list = list()
  focal = comp_trinuc[[1]]
  Nsig = nrow(focal) - 1
  Ncolumns = ceiling(sqrt(Nsig))
  Nrows = ceiling(Nsig/Ncolumns)
  for (i in 1:Nsig){
    cosmic_cosine =  apply(prior_sigsC, MARGIN=2, FUN=function(X) cosine(X, focal[i,]) )
    mymax = max(cosmic_cosine)
    if(mymax > 0.8){
      whichmax = which(cosmic_cosine == mymax)
      cosmic_cosine_list[[i]] = c(colnames(prior_sigsC)[whichmax], mymax)
    }

    pcawg_cosine = apply(prior_sigsP, MARGIN=2, FUN=function(X) cosine(X, focal[i,]) )
    mymax = max(pcawg_cosine)
    if(mymax > 0.8){
      whichmax = which(pcawg_cosine == mymax)
      pcawg_cosine_list[[i]] = c(colnames(prior_sigsP)[whichmax], mymax)
    }
  }
cosmic_cosine = data.frame(do.call(rbind, cosmic_cosine_list))
pcawg_cosine = data.frame(do.call(rbind, pcawg_cosine_list))
pcawg_cosinehdp = pcawg_cosine[as.numeric(as.character(pcawg_cosine[,2])) > 0.85, ]
# 1            SBS40 0.860001391572126
# 2  Signature.blood 0.950166102541501
# 3             SBS9 0.983655091408639
# 4           SBS17b 0.897135272322891
# 7             SBS8 0.897740548795868
# 8            SBS18  0.96837089978586
# 9             SBS2 0.871771182101415
# 10           SBS56 0.921560209453616
# 12           SBS7a 0.932090343556656
# 14           SBS13 0.890300497736426
# 15           SBS31 0.978061762435787
##### OLD 
# 2  Signature.blood 0.954777238558228
# 3             SBS9 0.970375594973821
# 4             SBS9 0.871073151599768
# 5           SBS17b 0.893491246385025
# 7             SBS6 0.854317053259606
# 8             SBS8 0.876944218047855
# 9            SBS18 0.967084184973058
# 10           SBS56 0.932045825991365
intersect(pcawg_cosine12[,1], pcawg_cosinehdp[,1])
# [1] "SBS9"            "SBS17b"          "Signature.blood" "SBS8"
pcawg_cosine12 = read.table(file="/Users/hm8/sanger/lymphocyteExpansionSequenceAnalysis/metaAnalysis_pcawg_mm_ARGhscPBonly_KX001_KX002_KX003_tonsilMS_tonsilPS_stemcellCB2_ARGtreg_Aug2020/sigprofiler/pcawg_cosine12.txt", header=F, stringsAsFactors = F)
union(pcawg_cosine12[,1], pcawg_cosinehdp[,1])
 # [1] "SBS9"            "SBS36"           "SBS17b"          "Signature.blood" "SBS8"            "SBS7a"
 # [7] "SBS1"            "SBS6"            "SBS18"           "SBS56"
write.table(union(pcawg_cosine12[,1], pcawg_cosinehdp[,1]), "signatures_union_hdp_sigprofiler.txt", col.names = F, quote=F, row.names = F)

## cosmicV2
# cosmic_cosinehdp = cosmic_cosine[as.numeric(as.character(cosmic_cosine[,2])) > 0.85, ]
# # 1      Signature.5 0.882927617052135
# # 2      Signature.1 0.915988330206125
# # 3  Signature.blood 0.945223131713418
# # 4      Signature.9 0.968309165042948
# # 5     Signature.17 0.972558038839613
# # 6      Signature.5 0.853830279933273
# # 7      Signature.9 0.884915274102586
# # 8      Signature.8 0.935603938911783
# # 9     Signature.18 0.950433611875052
# # 10     Signature.2 0.899551137848546
# # 11    Signature.17 0.880892043545871
# # 13     Signature.7   0.9669893212975
# # 14    Signature.13 0.901578437110738
# cosmic_cosinehdp[,1] = c("Signature 5", "Signature 1", "Signature blood", "Signature 9",     "Signature 17",    "Signature 5", "Signature 9",     "Signature 8",     "Signature 18", "Signature 2", "Signature 17", "Signature 7","Signature 13")
# 
# cosmic_cosine12 = c("Signature 9", "Signature 17", "Signature blood", "Signature 19",     "Signature 2", "Signature 1")
# union(cosmic_cosinehdp[,1], cosmic_cosine12)
# 
# write.table(union(cosmic_cosine12, cosmic_cosinehdp[,1]), "signatures_union_hdp_sigprofiler_cosmic2.txt", col.names = F, quote=F, row.names = F)
```

